apiVersion: v1
kind: Service
metadata:
  name: smit-api-service
  namespace: default
  labels:
    app: smit-api
spec:
  type: LoadBalancer
  selector:
    app: smit-api
  ports:
  - port: 80
    targetPort: 1234
    protocol: TCP
    name: http
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: smit-api-clusterip
  namespace: default
  labels:
    app: smit-api
spec:
  type: ClusterIP
  selector:
    app: smit-api
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
    name: http